/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmo;

import javax.swing.JOptionPane;

/**
 *
 * @author jfba3
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboxBits = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMultiplicando = new javax.swing.JTextField();
        txtMultiplicador = new javax.swing.JTextField();
        lblError1 = new javax.swing.JLabel();
        lblError2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtResp = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        lblErrorNumeros = new javax.swing.JLabel();
        fonod = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuArLim = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuAcercaDe = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenuItem();
        menuTable = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Algorito de Booth");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Brian Mora, Juan Bustamante");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 46, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Seleccione el numero de bits: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 117, -1, -1));

        cboxBits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "8", "16" }));
        cboxBits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cboxBits, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 114, 55, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ingrese un Multiplicando: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 159, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Ingrese el Multiplicador:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 195, 159, -1));

        txtMultiplicando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMultiplicando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultiplicandoActionPerformed(evt);
            }
        });
        txtMultiplicando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMultiplicandoKeyTyped(evt);
            }
        });
        getContentPane().add(txtMultiplicando, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 159, 110, -1));

        txtMultiplicador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMultiplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultiplicadorActionPerformed(evt);
            }
        });
        txtMultiplicador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMultiplicadorKeyTyped(evt);
            }
        });
        getContentPane().add(txtMultiplicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 199, 110, -1));

        lblError1.setForeground(new java.awt.Color(255, 51, 51));
        lblError1.setText("Este campo no puede estar vacio.");
        getContentPane().add(lblError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        lblError2.setForeground(new java.awt.Color(255, 0, 51));
        lblError2.setText("Este campo no puede estar vacio.");
        getContentPane().add(lblError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        btnCalcular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 196, 105, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Respuesta esperada:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 251, -1, -1));

        txtResp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResp.setText("0");
        getContentPane().add(txtResp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 248, -1, -1));

        btnLimpiar.setText("Limpiar");
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 241, -1, -1));

        txtResultados.setColumns(20);
        txtResultados.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 271, 1149, 555));

        lblErrorNumeros.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorNumeros.setText("Los valores no pueden ser mayores a 15.");
        getContentPane().add(lblErrorNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        fonod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fonod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        fonod.setText("jLabel6");
        getContentPane().add(fonod, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 840));

        jMenu1.setText("Archivo");

        menuArLim.setText("Limpiar");
        jMenu1.add(menuArLim);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuBar.add(jMenu1);

        menuHelp.setText("Help");

        menuAcercaDe.setText("Acerca de...");
        menuHelp.add(menuAcercaDe);

        menuAyuda.setText("Ejemplo");
        menuHelp.add(menuAyuda);

        menuTable.setText("Tabla");
        menuHelp.add(menuTable);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtMultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultiplicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMultiplicadorActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtMultiplicandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultiplicandoActionPerformed
        
    }//GEN-LAST:event_txtMultiplicandoActionPerformed

    private void txtMultiplicandoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultiplicandoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo numeros.", "Error 404!", JOptionPane.ERROR_MESSAGE);
        }else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=44 
                 || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                 || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                 || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Numeros.","Error 404!", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_txtMultiplicandoKeyTyped

    private void txtMultiplicadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultiplicadorKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Numeros.","Error 404!", JOptionPane.ERROR_MESSAGE);
        }else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 
                 || (int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
                 || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
                 || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Numeros.","Error 404!", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_txtMultiplicadorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JComboBox<String> cboxBits;
    private javax.swing.JLabel fonod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblError1;
    public javax.swing.JLabel lblError2;
    public javax.swing.JLabel lblErrorNumeros;
    public javax.swing.JMenuItem menuAcercaDe;
    public javax.swing.JMenuItem menuArLim;
    public javax.swing.JMenuItem menuAyuda;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuHelp;
    public javax.swing.JMenuItem menuTable;
    public javax.swing.JTextField txtMultiplicador;
    public javax.swing.JTextField txtMultiplicando;
    public javax.swing.JLabel txtResp;
    public javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
